import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function AppSidebar() {
  return (
    <div className="w-64 bg-gray-900 text-white flex flex-col p-6 border-r border-gray-800 min-h-screen">
      <div className="text-2xl font-bold mb-8">Curate</div>
      <nav className="flex flex-col gap-4">
        <a
          href="/"
          className="text-left px-2 py-2 rounded hover:bg-gray-800"
        >
          Upload
        </a>
        <a
          href="/training-console"
          className="text-left px-2 py-2 rounded hover:bg-gray-800"
        >
          Training
        </a>
      </nav>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen">
          <AppSidebar />
          <div className="flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
